### ISSUE TITLE
AddressSanitizer: global-buffer-overflow gc.c:919 in `scan_arena`

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#46]
(2024-07-01: edited to keep stack trace up to date with `main`, and add more platform details)

With:

- libcon4m https://github.com/crashappsec/libcon4m/commit/14604adf6ca68c75a08360129d71beb63571c1d1
- x86_64
- Linux 6.9.7
- clang 17.0.6 or gcc 14.1.1 20240522

ASan complains when running `c4test` on any file:

```console
$ ./debug/c4test tests/basic1.c4m
address of the universe: 0x5f3d161155a0
info: Compiling: /foo/libcon4m/tests/basic1.c4m
info: Done processing: /foo/libcon4m/tests/basic1.c4m
****STARTING PROGRAM EXECUTION*****
****PROGRAM EXECUTION FINISHED*****

Passed 1 out of 1 run tests.
=================================================================
==10924==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5f3d16115770 at pc 0x5f3d156b44a2 bp 0x7fffbb103b50 sp 0x7fffbb103b40
READ of size 8 at 0x5f3d16115770 thread T0
SCARINESS: 23 (8-byte-read-global-buffer-overflow)
    #0 0x5f3d156b44a1 in scan_arena ../src/con4m/gc.c:919
    #1 0x5f3d156b505e in raw_trace ../src/con4m/gc.c:1009
    #2 0x5f3d156b5599 in c4m_collect_arena ../src/con4m/gc.c:1055
    #3 0x5f3d156b6019 in c4m_gc_thread_collect ../src/con4m/gc.c:1125
    #4 0x5f3d1566f3e6 in main ../src/tests/test.c:533
    #5 0x788f20239c87  (/usr/lib/libc.so.6+0x25c87) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #6 0x788f20239d4b in __libc_start_main (/usr/lib/libc.so.6+0x25d4b) (BuildId: 32a656aa5562eece8c59a585f5eacd6cf5e2307b)
    #7 0x5f3d156628a4 in _start (libcon4m/debug/c4test+0x4998a4) (BuildId: 19489650db0e47546d8ec39a9c30f060f548f6de)

0x5f3d16115770 is located 0 bytes after global variable 'c4m_bi_types' defined in '../src/con4m/types.c:242:22' (0x5f3d161155e0) of size 400
0x5f3d16115770 is located 48 bytes before global variable 'type_node_for_list_of_type_objects' defined in '../src/con4m/types.c:245:13' (0x5f3d161157a0) of size 8
SUMMARY: AddressSanitizer: global-buffer-overflow ../src/con4m/gc.c:919 in scan_arena
Shadow bytes around the buggy address:
  0x5f3d16115480: f9 f9 f9 f9 00 00 00 00 04 f9 f9 f9 f9 f9 f9 f9
  0x5f3d16115500: 00 00 00 00 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x5f3d16115580: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x5f3d16115600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x5f3d16115680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x5f3d16115700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f9]f9
  0x5f3d16115780: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9
  0x5f3d16115800: f9 f9 f9 f9 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9
  0x5f3d16115880: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x5f3d16115900: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x5f3d16115980: 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10924==ABORTING
```

**Comment by viega** [comment]
No clue what this is nor can I reproduce it.

**Comment by viega** [comment]
At this point I'm pretty sure everything from #5 down was it complaining about us doing a scan of potential junk on the stack, and then testing to see whether it's in range of the heap. This code all got rewritten to be breadth first, so it probably was a false positive, and this is a non-issue either way.

The first four seem more likely to be an actual issue, so I'm not closing this out until I have time to look at it.

**Comment by viega** [comment]
This can def be closed at this point.
