### ISSUE TITLE
SIGSEGV: enum

### ISSUE THREAD

**Issue by ee7** [crashappsec/libcon4m#53]
With:

- libcon4m https://github.com/crashappsec/libcon4m/commit/14604adf6ca68c75a08360129d71beb63571c1d1
- x86_64
- Linux 6.9.6
- clang 17.0.6

We see a segfault when running `c4test` with the `.c4m` file:

```text
enum foo { A = "bar" }
```

with ASan output:

```text
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x6369394c81d3 bp 0x7fffe44ced50 sp 0x7fffe44cec60 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
    #0 0x6369394c81d3 in check_used_global_variable libcon4m/debug/../src/con4m/compiler/check_pass.c:2723:59
    #1 0x6369394920c0 in validate_module_variables libcon4m/debug/../src/con4m/compiler/check_pass.c:2766:13
    #2 0x63693948be28 in module_check_pass libcon4m/debug/../src/con4m/compiler/check_pass.c:2793:5
    #3 0x63693948ae61 in c4m_check_pass libcon4m/debug/../src/con4m/compiler/check_pass.c:3001:24
    #4 0x63693941def4 in c4m_compile_from_entry_point libcon4m/debug/../src/con4m/compiler/compile.c:1065:5
    #5 0x6369392a26a5 in test_compiler libcon4m/debug/../src/tests/test.c:425:11
    #6 0x6369392a54e2 in main libcon4m/debug/../src/tests/test.c:515:18
```

or the `.c4m` file:

```text
enum foo { A = 42 }
```

with ASan output:

```text
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x58375f373b8c bp 0x7ffcd2757490 sp 0x7ffcd2757100 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
    #0 0x58375f373b8c in type_hash_and_dedupe libcon4m/debug/../src/con4m/types.c:370:23
    #1 0x58375f372d28 in c4m_calculate_type_hash libcon4m/debug/../src/con4m/types.c:433:12
    #2 0x58375f375dc0 in tspec_copy_internal libcon4m/debug/../src/con4m/types.c:567:5
    #3 0x58375f374dca in c4m_type_copy libcon4m/debug/../src/con4m/types.c:578:12
    #4 0x58375f4b3cc4 in c4m_types_are_compat libcon4m/debug/../include/con4m/type.h:491:10
    #5 0x58375f4b3c94 in c4m_obj_type_check libcon4m/debug/../include/con4m/type.h:512:12
    #6 0x58375f4b1f15 in obj_type_check libcon4m/debug/../src/con4m/compiler/decl_pass.c:37:16
    #7 0x58375f4a3f8d in handle_enum_decl libcon4m/debug/../src/con4m/compiler/decl_pass.c:265:22
    #8 0x58375f4a2608 in pass_dispatch libcon4m/debug/../src/con4m/compiler/decl_pass.c:1386:9
    #9 0x58375f4b098e in process_children libcon4m/debug/../src/con4m/compiler/decl_pass.c:22:9
    #10 0x58375f4a2918 in pass_dispatch libcon4m/debug/../src/con4m/compiler/decl_pass.c:1427:9
    #11 0x58375f4a1cee in c4m_file_decl_pass libcon4m/debug/../src/con4m/compiler/decl_pass.c:1505:5
    #12 0x58375f44fc25 in c4m_initial_load_one libcon4m/debug/../src/con4m/compiler/compile.c:625:13
    #13 0x58375f44f688 in c4m_perform_module_loads libcon4m/debug/../src/con4m/compiler/compile.c:741:13
    #14 0x58375f451d0c in c4m_compile_from_entry_point libcon4m/debug/../src/con4m/compiler/compile.c:1053:5
    #15 0x58375f2d66a5 in test_compiler libcon4m/debug/../src/tests/test.c:425:11
    #16 0x58375f2d94e2 in main libcon4m/debug/../src/tests/test.c:515:18
```

---

It looks like the grammar currently specifies that there should be no curly braces:

```
enumStmt     ::= "enum" enumItem (',' enumItem)* EOS
enumItem     ::= ID (('=' | ':') expression)?
```

But omitting them, like:

```
enum A, B
```

produces the error:

```
Expected a { token here (expected_token)
```

**Comment by viega** [comment]
Yes, the grammar isn't updated, and the semantics aren't done. Enums shouldn't work yet.

**Comment by viega** [comment]
I've confirmed this all works at this point, btw.  I did just update the doc in my dev branch, but the rest of it has been working as intended... braces are required, and the enum can be named, even though the name is totally not used yet.
